[package]
name = "scoop2c"
version.workspace = true
edition.workspace = true

[[bin]]
name = "scoop2c"
path = "src/main.rs"

[dependencies]
scoop2_archive = { path = "../scoop2_archive" }
scoop2_base = { path = "../scoop2_base" }
scoop2_syntax = { path = "../scoop2_syntax" }
scoop2_hir = { path = "../scoop2_hir" }
scoop2_mir = { path = "../scoop2_mir" }
scoop2_lir = { path = "../scoop2_lir" }
scoop2_codegen_llvm = { path = "../scoop2_codegen_llvm" }
