use super::*;

impl Concretizer<'_> {
    pub(super) fn lower_callable(
        &mut self,
        source: export::Callable,
        substitution: &[concrete::TypeId],
    ) -> concrete::Callable {
        self.lower_callable_with_arguments(source, substitution).0
    }

    /// Resolve a template-only bound member from the explicit conformance map
    /// generated by export HIR. The returned interface is present only when
    /// dispatch must use the bound interface directly (an interface receiver
    /// or an abstract subclass-provided implementation).
    pub(super) fn resolve_bound_callee(
        &mut self,
        source: export::BoundCallableRefId,
        receiver: concrete::TypeId,
        substitution: &[concrete::TypeId],
    ) -> (concrete::Callable, Option<concrete::InterfaceId>) {
        let bound = self.source.bound_callable_refs[source].clone();
        let export::BoundCallableSource::Interface {
            bound: interface_bound,
            member,
        } = bound.source
        else {
            let export::BoundCallableSource::Class {
                bound: class_bound,
                callable,
            } = bound.source
            else {
                unreachable!("bound callable sources are class or interface members")
            };
            self.lower_class_application(class_bound, substitution);
            return (self.lower_callable(callable, substitution), None);
        };
        let required_interface = self.lower_interface_application(interface_bound, substitution);
        match self.types[receiver].kind.clone() {
            concrete::TypeKind::Integer(kind) => {
                let export::CoreProtocols::Defined(protocols) = self.core else {
                    panic!("imported-core HIR must encode core bound calls as imported uses")
                };
                let source = protocols.fundamental_types.integers.owner(kind);
                let conformances = self.source.structs[source]
                    .interface_implementations
                    .clone();
                self.resolve_nominal_bound_target(&conformances, &[], member, required_interface)
            }
            concrete::TypeKind::Boolean => {
                let export::CoreProtocols::Defined(protocols) = self.core else {
                    panic!("imported-core HIR must encode Boolean bound calls as imported uses")
                };
                let source = protocols.fundamental_types.boolean;
                let conformances = self.source.structs[source]
                    .interface_implementations
                    .clone();
                self.resolve_nominal_bound_target(&conformances, &[], member, required_interface)
            }
            concrete::TypeKind::String => {
                let export::CoreProtocols::Defined(protocols) = self.core else {
                    panic!("imported-core HIR must encode String bound calls as imported uses")
                };
                let source = protocols.fundamental_types.string;
                let conformances = self.source.classes[source]
                    .interface_implementations
                    .clone();
                self.resolve_nominal_bound_target(&conformances, &[], member, required_interface)
            }
            concrete::TypeKind::Struct(id) => {
                let source = self.struct_source[&id];
                let arguments = self.structs[id].type_arguments.clone();
                let conformances = self.source.structs[source]
                    .interface_implementations
                    .clone();
                self.resolve_nominal_bound_target(
                    &conformances,
                    &arguments,
                    member,
                    required_interface,
                )
            }
            concrete::TypeKind::Enum(id) => {
                let source = self.enum_source[&id];
                let arguments = self.enums[id].type_arguments.clone();
                let conformances = self.source.enums[source].interface_implementations.clone();
                self.resolve_nominal_bound_target(
                    &conformances,
                    &arguments,
                    member,
                    required_interface,
                )
            }
            concrete::TypeKind::Class(id) => {
                let source = self.class_source[&id];
                let arguments = self.classes[id].type_arguments.clone();
                let conformances = self.source.classes[source]
                    .interface_implementations
                    .clone();
                self.resolve_nominal_bound_target(
                    &conformances,
                    &arguments,
                    member,
                    required_interface,
                )
            }
            concrete::TypeKind::Interface(_) => {
                let application = self.source.interface_applications[interface_bound].clone();
                let arguments = application
                    .arguments
                    .iter()
                    .map(|argument| self.lower_type(*argument, substitution))
                    .collect();
                let function = self.source.interface_methods[member].function;
                (
                    concrete::Callable::Function(self.request_function(function, arguments)),
                    Some(required_interface),
                )
            }
            kind => panic!(
                "bound receiver reached concretization without an explicit conformance: {kind:?}"
            ),
        }
    }

    pub(super) fn resolve_nominal_bound_target(
        &mut self,
        conformances: &[export::InterfaceImplementation],
        owner_arguments: &[concrete::TypeId],
        member: export::InterfaceMethodId,
        required_interface: concrete::InterfaceId,
    ) -> (concrete::Callable, Option<concrete::InterfaceId>) {
        for conformance in conformances {
            let interface = self.lower_interface_type(conformance.interface, owner_arguments);
            if interface != required_interface {
                continue;
            }
            let implementation = conformance
                .methods
                .iter()
                .find(|implementation| {
                    implementation.member == export::InterfaceMethodReference::Local(member)
                })
                .unwrap_or_else(|| {
                    panic!("export HIR conformance omits a required interface method")
                });
            return match &implementation.target {
                export::InterfaceImplementationTarget::ImportedTemplate(application) => (
                    concrete::Callable::Function(self.lower_imported_callable_application(
                        &self.source.imported_generic_applications[*application],
                        owner_arguments,
                    )),
                    None,
                ),
                export::InterfaceImplementationTarget::Method(application) => (
                    self.lower_method_application(*application, owner_arguments),
                    None,
                ),
                export::InterfaceImplementationTarget::Abstract(_)
                | export::InterfaceImplementationTarget::ImportedAbstractTemplate(_)
                | export::InterfaceImplementationTarget::Imported(_)
                | export::InterfaceImplementationTarget::ImportedAbstract(_) => {
                    let function = self.source.interface_methods[member].function;
                    (
                        concrete::Callable::Function(self.request_method(
                            function,
                            concrete::MethodOwner::Interface(required_interface),
                            MethodRequest::Plain,
                        )),
                        Some(required_interface),
                    )
                }
            };
        }
        panic!("export HIR has no explicit conformance for a validated bound call")
    }

    pub(super) fn adapt_receiver_to_interface(
        &mut self,
        receiver: concrete::Expr,
        interface: concrete::InterfaceId,
    ) -> concrete::Expr {
        let target = self.interface_type[&interface];
        if receiver.ty == target {
            return receiver;
        }
        let span = receiver.span;
        let origin = receiver.origin;
        let value = matches!(
            self.types[receiver.ty].kind,
            concrete::TypeKind::Unit
                | concrete::TypeKind::Integer(_)
                | concrete::TypeKind::Boolean
                | concrete::TypeKind::Struct(_)
                | concrete::TypeKind::Enum(_)
                | concrete::TypeKind::Tuple(_)
                | concrete::TypeKind::Ptr(_)
                | concrete::TypeKind::FunPtr(_)
        );
        if value {
            self.ensure_box_source(receiver.ty);
            concrete::Expr {
                kind: concrete::ExprKind::Box(Box::new(receiver)),
                ty: target,
                span,
                origin,
            }
        } else {
            concrete::Expr {
                kind: receiver.kind,
                ty: target,
                span,
                origin,
            }
        }
    }

    pub(super) fn lower_callable_with_arguments(
        &mut self,
        source: export::Callable,
        substitution: &[concrete::TypeId],
    ) -> (concrete::Callable, Vec<concrete::TypeId>) {
        match source {
            export::Callable::Function(function) => {
                assert!(
                    self.source.functions[function].type_param_count() == 0,
                    "a parameterized callable uses a resolved generic identity"
                );
                (
                    concrete::Callable::Function(self.request_function(function, Vec::new())),
                    Vec::new(),
                )
            }
            export::Callable::Generic(resolved) => {
                let resolved = self.source.instantiations[resolved].clone();
                let function = self.source.generic_functions[resolved.generic].function;
                let arguments: Vec<_> = resolved
                    .type_args
                    .iter()
                    .map(|argument| self.lower_type(*argument, substitution))
                    .collect();
                (
                    concrete::Callable::Function(
                        self.request_function(function, arguments.clone()),
                    ),
                    arguments,
                )
            }
            export::Callable::Method(application) => {
                self.lower_method_application_with_arguments(application, substitution)
            }
            export::Callable::GenericMethod(application) => {
                let application = self.source.generic_method_applications[application].clone();
                let owner = self.lower_generic_method_owner(application.owner, substitution);
                let method_arguments = export::NonEmptyVec::from_vec(
                    application
                        .method_arguments
                        .iter()
                        .map(|argument| self.lower_type(*argument, substitution))
                        .collect(),
                )
                .expect("export generic method applications are non-empty");
                let mut arguments = self.concrete_method_owner_arguments(owner).to_vec();
                arguments.extend(method_arguments.iter().copied());
                let function = self.source.generic_methods[application.method].function;
                let concrete = self.request_method(
                    function,
                    owner,
                    MethodRequest::Generic {
                        definition: application.method,
                        method_arguments,
                    },
                );
                (concrete::Callable::Function(concrete), arguments)
            }
        }
    }

    pub(super) fn lower_method_application(
        &mut self,
        source: export::MethodApplicationId,
        substitution: &[concrete::TypeId],
    ) -> concrete::Callable {
        self.lower_method_application_with_arguments(source, substitution)
            .0
    }

    pub(super) fn lower_method_application_with_arguments(
        &mut self,
        source: export::MethodApplicationId,
        substitution: &[concrete::TypeId],
    ) -> (concrete::Callable, Vec<concrete::TypeId>) {
        let application = self.source.method_applications[source].clone();
        let owner = self.lower_method_owner(application.owner, substitution);
        let arguments = self.concrete_method_owner_arguments(owner).to_vec();
        let function = self.request_method(application.function, owner, MethodRequest::Plain);
        (concrete::Callable::Function(function), arguments)
    }

    pub(super) fn lower_derived_equality_application(
        &mut self,
        source: export::DerivedEqualityApplicationId,
        substitution: &[concrete::TypeId],
    ) -> concrete::Callable {
        let application = self.source.derived_equality_applications[source].clone();
        match application.origin {
            export::DerivedEqualityOrigin::Nominal(owner) => {
                let owner = self.lower_method_owner(owner, substitution);
                let key = FunctionKey::Method {
                    source: application.function,
                    owner,
                    specialization: MethodRequest::Plain,
                };
                if !self.derived_bodies.contains_key(&key) {
                    let body = self.lower_body(&application.body, substitution);
                    self.derived_bodies.insert(key.clone(), body);
                }
                concrete::Callable::Function(self.request_function_key(key))
            }
            export::DerivedEqualityOrigin::Structural(source_owner_ty) => {
                debug_assert_eq!(source_owner_ty, application.owner_ty);
                let owner_ty = self.lower_type(application.owner_ty, substitution);
                let cache_key = (source, owner_ty);
                if let Some(&function) = self.structural_derived_functions.get(&cache_key) {
                    return concrete::Callable::Function(function);
                }

                // Reserve and publish the identity before lowering the body,
                // so nested structural applications can refer back to it
                // without requiring a downstream recursion heuristic.
                let raw = self.function_slots.len() as u32;
                self.function_slots.push(None);
                self.function_keys.push(FunctionKey::Method {
                    source: application.function,
                    owner: concrete::MethodOwner::Structural(owner_ty),
                    specialization: MethodRequest::Plain,
                });
                let function = concrete::FunctionId::from_raw(raw.into());
                self.structural_derived_functions
                    .insert(cache_key, function);

                let (body, local_map) = self.lower_body(&application.body, substitution);
                let source_function = &self.source.functions[application.function];
                let params = source_function
                    .params
                    .iter()
                    .map(|param| concrete::Param {
                        name: param.name.clone(),
                        ty: owner_ty,
                        local: local_map[param.local.into_raw().into_u32() as usize],
                    })
                    .collect();
                let value = PendingFunction {
                    name: format!("$derived.equals.{}", source.into_raw().into_u32()),
                    is_suspend: false,
                    modifiers: export::CallableModifiers {
                        operator: Some(export::OperatorKind::Equals),
                        property_delegate_operator: None,
                        is_infix: false,
                    },
                    params,
                    capture_parameters: Vec::new(),
                    return_ty: self.lower_type(source_function.return_ty, substitution),
                    attributes: application.attributes,
                    kind: concrete::FunctionKind::User(body),
                    receiver: concrete::FunctionReceiver::Method(concrete::Method {
                        owner: owner_ty,
                        modifier: concrete::MethodModifier::Final,
                        dispatch: concrete::MethodDispatch::Direct,
                    }),
                    span: application.span,
                };
                let slot = function.into_raw().into_u32() as usize;
                assert!(self.function_slots[slot].replace(value).is_none());
                self.emitted_functions.push(function);
                concrete::Callable::Function(function)
            }
        }
    }

    pub(super) fn lower_method_owner(
        &mut self,
        owner: export::MethodOwnerApplication,
        substitution: &[concrete::TypeId],
    ) -> concrete::MethodOwner {
        match owner {
            export::MethodOwnerApplication::Class(id) => {
                concrete::MethodOwner::Class(self.lower_class_application(id, substitution))
            }
            export::MethodOwnerApplication::Struct(id) => {
                concrete::MethodOwner::Struct(self.lower_struct_application(id, substitution))
            }
            export::MethodOwnerApplication::Enum(id) => {
                concrete::MethodOwner::Enum(self.lower_enum_application(id, substitution))
            }
            export::MethodOwnerApplication::Interface(id) => {
                concrete::MethodOwner::Interface(self.lower_interface_application(id, substitution))
            }
            export::MethodOwnerApplication::Object(id) => {
                concrete::MethodOwner::Object(self.lower_object_type(id))
            }
        }
    }

    pub(super) fn lower_generic_method_owner(
        &mut self,
        owner: export::GenericMethodOwner,
        substitution: &[concrete::TypeId],
    ) -> concrete::MethodOwner {
        match owner {
            export::GenericMethodOwner::Class(id) => {
                concrete::MethodOwner::Class(self.lower_class_application(id, substitution))
            }
            export::GenericMethodOwner::Struct(id) => {
                concrete::MethodOwner::Struct(self.lower_struct_application(id, substitution))
            }
            export::GenericMethodOwner::Enum(id) => {
                concrete::MethodOwner::Enum(self.lower_enum_application(id, substitution))
            }
            export::GenericMethodOwner::Object(id) => {
                concrete::MethodOwner::Object(self.lower_object_type(id))
            }
        }
    }

    pub(super) fn lower_place(
        &self,
        source: export::Place,
        locals: &[concrete::LocalId],
    ) -> concrete::Place {
        match source {
            export::Place::Local(local) => concrete::Place::Local(self.lower_local(local, locals)),
            export::Place::Global(global) => concrete::Place::Global(self.global_map[&global]),
        }
    }

    pub(super) fn lower_field_ref(
        &mut self,
        source: export::FieldRef,
        substitution: &[concrete::TypeId],
    ) -> concrete::FieldRef {
        match source {
            export::FieldRef::ImportedClass { owner, field } => {
                let ty = self.lower_type(owner, substitution);
                let concrete::TypeKind::Class(class_id) = self.types[ty].kind else {
                    unreachable!("a dependency class field retains its class owner")
                };
                self.imported_class_field_ref(class_id, field)
            }
            export::FieldRef::ImportedStruct { owner, field } => {
                let ty = self.lower_type(owner, substitution);
                let concrete::TypeKind::Struct(structure) = self.types[ty].kind else {
                    unreachable!("a dependency struct field retains its struct receiver")
                };
                let index = self.structs[structure]
                    .declared_fields()
                    .iter()
                    .position(|candidate| candidate.identity == field)
                    .expect("a resolved dependency field belongs to its declaration");
                concrete::FieldRef::StructField(
                    concrete::StructFieldRef::checked(&self.structs, structure, index as u32)
                        .expect("a declared dependency field is in range"),
                )
            }
            export::FieldRef::StructField(field) => concrete::FieldRef::StructField(
                self.lower_applied_struct_field_ref(field, substitution),
            ),
            export::FieldRef::TupleIndex(index) => concrete::FieldRef::TupleIndex(index),
            export::FieldRef::ClassField { application, field } => {
                let concrete_id = self.lower_class_application(application, substitution);
                let index = self.source_class_field_layout_index(field);
                concrete::FieldRef::ClassField {
                    class_id: concrete_id,
                    index,
                }
            }
        }
    }

    pub(super) fn lower_applied_struct_field_ref(
        &mut self,
        source: export::AppliedStructFieldRef,
        substitution: &[concrete::TypeId],
    ) -> concrete::StructFieldRef {
        let structure = self.lower_struct_application(source.application(), substitution);
        concrete::StructFieldRef::checked(&self.structs, structure, source.local_index())
            .expect("a checked applied struct field concretizes to the same declared field")
    }

    pub(super) fn lower_applied_enum_variant_ref(
        &mut self,
        source: export::AppliedEnumVariantRef,
        substitution: &[concrete::TypeId],
    ) -> concrete::EnumVariantRef {
        let enumeration = self.lower_enum_application(source.application(), substitution);
        let variant = concrete::VariantId::from_raw(source.local_index());
        concrete::EnumVariantRef::checked(&self.enums, enumeration, variant)
            .expect("a checked applied enum variant concretizes to the same variant")
    }

    pub(super) fn lower_applied_enum_variant_field_ref(
        &mut self,
        source: export::AppliedEnumVariantFieldRef,
        substitution: &[concrete::TypeId],
    ) -> concrete::EnumVariantFieldRef {
        let variant = self.lower_applied_enum_variant_ref(source.variant(), substitution);
        concrete::EnumVariantFieldRef::checked(&self.enums, variant, source.local_index())
            .expect("a checked applied enum field concretizes to the same payload field")
    }

    pub(super) fn source_class_field_layout_index(&self, field: export::ClassFieldId) -> u32 {
        let declaration = &self.source.class_fields[field];
        let own = self.source.classes[declaration.owner]
            .fields
            .iter()
            .position(|candidate| *candidate == field)
            .expect("a class field is listed by its typed owner") as u32;
        let mut base_count = 0_u32;
        let mut current = self.source.classes[declaration.owner].base_class;
        while let Some(base) = current {
            let fields = match &self.source.types[base] {
                export::Type::Class(application) => {
                    let class =
                        &self.source.classes[self.source.class_applications[*application].template];
                    current = class.base_class;
                    class.fields.len()
                }
                export::Type::ImportedClass(class) => {
                    current = class.base_class;
                    class.fields.len()
                }
                _ => unreachable!("validated class bases have class types"),
            };
            base_count = base_count
                .checked_add(u32::try_from(fields).expect("class field indices fit in u32"))
                .expect("class field indices fit in u32");
        }
        base_count + own
    }

    pub(super) fn lower_local(
        &self,
        source: export::LocalId,
        locals: &[concrete::LocalId],
    ) -> concrete::LocalId {
        locals[source.into_raw().into_u32() as usize]
    }

    pub(super) fn lower_capture(
        &mut self,
        source: &export::Capture,
        substitution: &[concrete::TypeId],
        locals: &[concrete::LocalId],
    ) -> concrete::Capture {
        concrete::Capture {
            binding: concrete::BindingId::from_raw(source.binding.into_raw()),
            name: source.name.clone(),
            ty: self.lower_type(source.ty, substitution),
            first_use_span: source.first_use_span,
            source: self.lower_expr(&source.source, substitution, locals),
        }
    }
}
