[package]
name = "scoopc_project_model"
version.workspace = true
edition.workspace = true

[dependencies]
miette = { version = "7.6.0", features = ["fancy"] }
scoopc_ids = { path = "../scoopc_ids" }
scoopc_source = { path = "../scoopc_source" }
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.12"
toml = "0.8.23"
