[package]
name = "scoop"
edition.workspace = true
rust-version.workspace = true

[dependencies]
scoop-identity.workspace = true
scoop-manifest.workspace = true
scoop-lir.workspace = true
scoop-linker.workspace = true
scoop-protocol.workspace = true
scoop-slib.workspace = true
scoop-toolchain.workspace = true
scoop-wire.workspace = true
tempfile.workspace = true
fs4.workspace = true

[target.'cfg(unix)'.dependencies]
rustix.workspace = true

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true
