[workspace]
resolver = "2"
members = [
    "crates/scoop",
    "crates/scoopld",
    "crates/scoopc",
    "crates/scoopc_ast",
    "crates/scoopc_codegen_llvm",
    "crates/scoopc_cone",
    "crates/scoopc_effect_facts_stage",
    "crates/scoopc_hir",
    "crates/scoopc_lir",
    "crates/scoopc_mir",
    "crates/scoopc_span",
    "crates/scoopc_source",
    "crates/scoopc_types",
    "crates/scoopc_ids",
    "crates/scoop_project_model",
    "crates/scoopc_hir_facts",
    "crates/scoopc_mir_facts",
    "crates/scoopc_effect_facts",
    "crates/scoopc_lir_facts",
    "crates/scoop_runtime",
    "crates/scoop2_base",
    "crates/scoop2_syntax",
    "crates/scoop2_hir",
    "crates/scoop2_mir",
    "crates/scoop2_lir",
    "crates/scoop2_codegen_llvm",
    "crates/scoop2c",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
