[package]
name = "scoop2_archive"
version.workspace = true
edition.workspace = true

[dependencies]
scoop2_lir = { path = "../scoop2_lir" }
bincode = { workspace = true }
serde = { workspace = true }
scoop2_base = { path = "../scoop2_base" }
scoop2_hir = { path = "../scoop2_hir" }
scoop2_mir = { path = "../scoop2_mir" }
scoop2_syntax = { path = "../scoop2_syntax" }
