[package]
name = "scoopc_cone"
version.workspace = true
edition.workspace = true

[dependencies]
scoopc_ast = { path = "../scoopc_ast" }
scoopc_codegen_llvm = { path = "../scoopc_codegen_llvm", default-features = false }
scoopc_effect_facts = { path = "../scoopc_effect_facts" }
scoopc_effect_facts_stage = { path = "../scoopc_effect_facts_stage" }
scoopc_hir = { path = "../scoopc_hir" }
scoopc_hir_facts = { path = "../scoopc_hir_facts" }
scoopc_ids = { path = "../scoopc_ids" }
scoopc_lir = { path = "../scoopc_lir" }
scoopc_lir_facts = { path = "../scoopc_lir_facts" }
scoopc_mir = { path = "../scoopc_mir" }
scoopc_mir_facts = { path = "../scoopc_mir_facts" }
scoopc_project_model = { path = "../scoopc_project_model" }
scoopc_source = { path = "../scoopc_source" }
scoopc_span = { path = "../scoopc_span" }
scoopc_types = { path = "../scoopc_types" }
miette = { version = "7.6.0", features = ["fancy"] }
thiserror = "2.0.12"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tar = "0.4.44"
sha2 = "0.10.9"
