#[test]
fn generic_global_state_republishes_and_executes_from_artifacts() {
    super::members::check_fixture_cases(
        "m23-global-state",
        &[
            "static",
            "no-gc",
            "order",
            "initialization",
            "values",
            "enum-state",
            "lexical",
            "members",
            "defaults",
            "delegated",
            "generic-initializer",
        ],
        &[
            "bad-private",
            "bad-internal",
            "bad-public-default",
            "bad-readonly",
            "bad-setter",
            "bad-type",
            "bad-no-gc-runtime",
            "bad-no-gc-body",
            "bad-no-gc-reference",
        ],
        "downstream",
    );
}
