#[test]
fn imported_iteration_rejections_have_source_diagnostics() {
    super::members::check_fixture_cases(
        "m23-iteration",
        &[],
        &[
            "missing-operator",
            "wrong-protocol",
            "multiple-applications",
            "private-operator",
            "refutable-pattern",
            "immutable-binding",
            "escaping-break",
            "suspend-context",
            "shadow-protocol",
            "no-gc",
            "binding-arity",
        ],
        "downstream",
    );
}
