#[test]
fn source_callable_references_republish_and_execute_from_artifacts() {
    super::members::check_fixture_cases(
        "m23-source-callable-references",
        &[
            "named",
            "generic",
            "extensions",
            "primitives",
            "members",
            "protected",
            "dispatch",
            "bounds",
            "overloads",
            "layers",
            "defaults",
            "lexical",
            "values",
        ],
        &[
            "bad-generic",
            "bad-owner-inference",
            "bad-overload",
            "bad-ambiguous",
            "bad-protected",
            "bad-result",
            "bad-default-arity",
            "bad-kind",
            "bad-unsafe",
            "bad-suspend",
            "bad-generic-member",
            "bad-unbound-member",
            "bad-constructor",
        ],
        "downstream",
    );
}
