//! Canonical public semantic interface shared across Cone boundaries.

mod binders;
mod callable_interfaces;
mod callable_source_interfaces;
mod canonical_ids;
mod const_values;
mod declaration_common;
mod declaration_references;
mod default_templates;
mod definition_sources;
mod nominal_interfaces;
mod nominal_shapes;
mod property_interfaces;
mod public_bindings;
mod route_closure;
mod type_alias_interfaces;

pub use binders::{
    BinderListValidationError, CanonicalBinderListV1, CanonicalSignatureTypesV1,
    DecodedCanonicalBinderListV1, DecodedCanonicalSignatureTypesV1,
    DecodedNominalTypeParameterBoundsV1, DecodedTypeParameterBinderV1,
    DecodedTypeParameterBoundsV1, MeteredSignatureTypeSemanticError, NominalBoundSemanticError,
    NominalInterfaceShapeAuthority, NominalSignatureSemanticError, NominalTypeParameterBoundsV1,
    PublicNominalShapeV1, SignatureBinderScopeError, SignatureBinderScopeV1, SignatureTypeFormV1,
    SignatureTypeReferenceResolver, SignatureTypeSemanticError, SignatureTypeSetBuildError,
    SignatureTypeSetValidationError, TypeParameterBinderBuildError,
    TypeParameterBinderResolutionError, TypeParameterBinderScopeValidationError,
    TypeParameterBinderSemanticValidationError, TypeParameterBinderV1, TypeParameterBoundLocation,
    TypeParameterBoundsBuildError, TypeParameterBoundsResolutionError, TypeParameterBoundsV1,
};
pub use callable_interfaces::{
    CallableDeclarationIdentityShapeV1, CallableImplementationV1, CallableInfixV1,
    CallableInterfaceRecordBuildError, CallableInterfaceRecordResolutionError,
    CallableInterfaceRecordResolver, CallableInterfaceRecordV1, CallableInterfaceSemanticAuthority,
    CallableInterfaceSemanticValidationError, CallableInterfaceSetBuildError,
    CallableInterfaceSetSemanticValidationError, CallableInterfaceSetValidationError,
    CallableModalityV1, CallableOperatorRoleV1, CallableOperatorV1, CallableSafetyV1,
    CallableSourceEffectsBuildError, CallableSourceEffectsV1, CanonicalCallableInterfacesV1,
    CanonicalSourceParameterShapesV1, DecodedCallableInterfaceRecordV1,
    DecodedCallableSourceEffectsV1, DecodedCanonicalCallableInterfacesV1,
    DecodedCanonicalSourceParameterShapesV1, DecodedSourceParameterShapeV1,
    PropertyDelegateOperatorV1, PublicLookupAccessV1, SourceParameterListBuildError,
    SourceParameterListValidationError, SourceParameterShapeResolutionError,
    SourceParameterShapeV1,
};
pub use callable_source_interfaces::{
    CallableParameterCallingResolutionError, CallableParameterCallingV1,
    CallableSourceInterfaceBuildError, CallableSourceInterfaceIndexError,
    CallableSourceInterfaceResolutionError, CallableSourceInterfaceSemanticAuthority,
    CallableSourceInterfaceSemanticValidationError, CallableSourceInterfaceSetBuildError,
    CallableSourceInterfaceSetIndexError, CallableSourceInterfaceSetSemanticValidationError,
    CallableSourceInterfaceSetValidationError, CallableSourceInterfaceV1,
    CallableSourceParameterListBuildError, CallableSourceParameterListResolutionError,
    CallableSourceParameterResolutionError, CallableSourceParameterV1,
    CanonicalCallableSourceInterfacesV1, CanonicalCallableSourceParametersV1,
    DecodedCallableParameterCallingV1, DecodedCallableSourceInterfaceV1,
    DecodedCallableSourceParameterV1, DecodedCanonicalCallableSourceInterfacesV1,
    DecodedCanonicalCallableSourceParametersV1, ExportDefaultTemplateIndexResolver,
    ExportDefaultTemplateKeyResolver, IndexedCallableSourceInterfaceV1,
    IndexedCanonicalCallableSourceInterfacesV1,
};
pub use canonical_ids::{
    CanonicalPersistentIdSetBuildError, CanonicalPersistentIdSetValidationError,
    CanonicalPersistentIdsV1, DecodedCanonicalPersistentIdsV1,
};
pub use const_values::{
    CanonicalBooleanV1, CanonicalConstValueKindV1, CanonicalConstValueV1,
    CanonicalExportConstValuesV1, CanonicalIntegerConstantV1, ConstPropertyDeclarationSourceV1,
    DecodedCanonicalExportConstValuesV1, DecodedExportConstValueV1,
    ExportConstValueClosureValidationError, ExportConstValueResolutionError,
    ExportConstValueResolver, ExportConstValueSemanticAuthority,
    ExportConstValueSemanticValidationError, ExportConstValueSetBuildError,
    ExportConstValueSetSemanticValidationError, ExportConstValueSetValidationError,
    ExportConstValueV1,
};
pub use declaration_common::{
    DecodedPublicDeclarationOwnerV1, PublicDeclarationOwnerV1, PublicNominalKindV1,
    UnsupportedPublicNominalKind,
};
pub use declaration_references::{
    CallableDeclarationId, CallableDeclarationIdResolver, CanonicalPublicMemberRefsV1,
    DecodedCallableDeclarationId, DecodedCanonicalPublicMemberRefsV1, DecodedPropertyDeclarationId,
    DecodedPublicMemberRefV1, DecodedSourceNominalId, PropertyDeclarationId,
    PropertyDeclarationIdResolver, PublicMemberRefBuildError, PublicMemberRefResolver,
    PublicMemberRefSetValidationError, PublicMemberRefV1, SourceNominalId, SourceNominalIdResolver,
};
pub use default_templates::{
    BinderUseListBuildError, BinderUseListSemanticValidationError, BinderUseListValidationError,
    CanonicalBinderUseListV1, CanonicalExportDefaultTemplatesV1, CanonicalTemplateLocalTableV1,
    CanonicalTemplateValueParametersV1, DecodedCanonicalBinderUseListV1,
    DecodedCanonicalExportDefaultTemplatesV1, DecodedCanonicalTemplateLocalTableV1,
    DecodedCanonicalTemplateValueParametersV1, DecodedDefaultAnonymousFunctionV1,
    DecodedDefaultAppliedOptionV1, DecodedDefaultArrayAssemblyPartV1,
    DecodedDefaultArrayAssemblyV1, DecodedDefaultAssignTargetV1, DecodedDefaultBindingActionV1,
    DecodedDefaultBindingClassComponentV1, DecodedDefaultBindingLeafV1,
    DecodedDefaultBindingPlanV1, DecodedDefaultBindingProjectionV1, DecodedDefaultBindingShapeV1,
    DecodedDefaultBindingStructFieldV1, DecodedDefaultBindingTemporaryV1,
    DecodedDefaultBoundCallableRefV1, DecodedDefaultBoundCallableSourceV1,
    DecodedDefaultCallableBodyTypeArgumentsV1, DecodedDefaultCallableDeclarationV1,
    DecodedDefaultCallableRefV1, DecodedDefaultCallableReferenceTargetV1,
    DecodedDefaultCallableReferenceV1, DecodedDefaultCaptureV1, DecodedDefaultCatchV1,
    DecodedDefaultClassConstructorIdV1, DecodedDefaultConstructorRefV1,
    DecodedDefaultEnumVariantFieldRefV1, DecodedDefaultEnumVariantRefV1,
    DecodedDefaultExpressionV1, DecodedDefaultFieldRefV1, DecodedDefaultForIterationPlanV1,
    DecodedDefaultIntegerArgumentsV1, DecodedDefaultIntegerOperationV1,
    DecodedDefaultIteratorConformanceV1, DecodedDefaultIteratorNextV1, DecodedDefaultLambdaV1,
    DecodedDefaultLiteralEqualityV1, DecodedDefaultLocalFunctionV1, DecodedDefaultMethodCalleeV1,
    DecodedDefaultPatternFieldV1, DecodedDefaultPatternV1, DecodedDefaultPlaceV1,
    DecodedDefaultStatementV1, DecodedDefaultStringOwnerV1, DecodedDefaultTryV1,
    DecodedDefaultWhenArmV1, DecodedDefaultWhenFallbackV1, DecodedDefaultWhenGuardV1,
    DecodedDefaultWhenV1, DecodedExportDefaultBodyV1, DecodedExportDefaultTemplateKeyV1,
    DecodedExportDefaultTemplateV1, DecodedOptionalDefaultExpressionV1,
    DecodedOptionalDefaultStatementListV1, DecodedOptionalDefaultWhenGuardV1,
    DecodedOptionalTemplateReceiverV1, DecodedPersistentLexicalRootV1,
    DecodedTemplateLocalDefinitionV1, DecodedTemplateLocalRecordV1, DecodedTemplateReceiverV1,
    DecodedTemplateValueParameterV1, DefaultAnonymousFunctionV1, DefaultAppliedOptionV1,
    DefaultArrayAccessKindV1, DefaultArrayAssemblyBuildError, DefaultArrayAssemblyPartV1,
    DefaultArrayAssemblyV1, DefaultAssignTargetIndexError, DefaultAssignTargetResolutionError,
    DefaultAssignTargetV1, DefaultBinaryOperatorV1, DefaultBinderRefV1,
    DefaultBindingActionBuildError, DefaultBindingActionV1, DefaultBindingActionViewV1,
    DefaultBindingClassComponentV1, DefaultBindingLeafIndexError,
    DefaultBindingLeafResolutionError, DefaultBindingLeafV1, DefaultBindingPlanBuildError,
    DefaultBindingPlanV1, DefaultBindingProjectionBuildError,
    DefaultBindingProjectionResolutionError, DefaultBindingProjectionV1,
    DefaultBindingProjectionViewV1, DefaultBindingShapeBuildError, DefaultBindingShapeIndexError,
    DefaultBindingShapeResolutionError, DefaultBindingShapeV1, DefaultBindingShapeViewV1,
    DefaultBindingStructFieldV1, DefaultBindingTemporaryIndexError,
    DefaultBindingTemporaryResolutionError, DefaultBindingTemporaryV1, DefaultBodyOriginSiteV1,
    DefaultBodyProviderEnvelopeSemanticValidationError, DefaultBodyProviderTypeSiteV1,
    DefaultBoundCallableRefResolutionError, DefaultBoundCallableRefV1,
    DefaultBoundCallableSourceResolutionError, DefaultBoundCallableSourceV1,
    DefaultCallableBodyTypeArgumentsBuildError, DefaultCallableBodyTypeArgumentsResolutionError,
    DefaultCallableBodyTypeArgumentsV1, DefaultCallableDeclarationV1, DefaultCallableRefBuildError,
    DefaultCallableRefResolutionError, DefaultCallableRefV1, DefaultCallableReferenceBuildError,
    DefaultCallableReferenceIndexError, DefaultCallableReferenceResolutionError,
    DefaultCallableReferenceResolver, DefaultCallableReferenceTargetV1, DefaultCallableReferenceV1,
    DefaultCaptureIndexError, DefaultCaptureResolutionError, DefaultCaptureV1, DefaultCatchV1,
    DefaultClassConstructorIdResolver, DefaultClassConstructorIdV1,
    DefaultConstructorRefResolutionError, DefaultConstructorRefV1,
    DefaultConstructorReferenceResolver, DefaultControlFlowBuildError,
    DefaultControlFlowIndexError, DefaultControlFlowResolutionError,
    DefaultEnumVariantFieldRefResolutionError, DefaultEnumVariantFieldRefV1,
    DefaultEnumVariantRefResolutionError, DefaultEnumVariantRefV1, DefaultExpressionBuildError,
    DefaultExpressionIndexError, DefaultExpressionKindV1, DefaultExpressionReferenceResolver,
    DefaultExpressionResolutionError, DefaultExpressionV1, DefaultFieldRefResolutionError,
    DefaultFieldRefV1, DefaultFieldReferenceResolver, DefaultForIterationPlanBuildError,
    DefaultForIterationPlanIndexError, DefaultForIterationPlanResolutionError,
    DefaultForIterationPlanV1, DefaultForeignCallbackOperationV1, DefaultIntegerArgumentsV1,
    DefaultIntegerDivRemV1, DefaultIntegerKindV1, DefaultIntegerOperationResolutionError,
    DefaultIntegerOperationV1, DefaultIteratorConformanceV1, DefaultIteratorNextV1,
    DefaultLambdaV1, DefaultLexicalCallableBuildError, DefaultLexicalCallableIndexError,
    DefaultLexicalCallableResolutionError, DefaultLiteralEqualityResolutionError,
    DefaultLiteralEqualityV1, DefaultLocalFunctionBuildError, DefaultLocalFunctionIndexError,
    DefaultLocalFunctionResolutionError, DefaultLocalFunctionV1,
    DefaultMethodCalleeResolutionError, DefaultMethodCalleeV1,
    DefaultNestedCallableReferenceResolver, DefaultNoGcIntegerOperationV1,
    DefaultPatternBuildError, DefaultPatternFieldV1, DefaultPatternIndexError,
    DefaultPatternReferenceResolver, DefaultPatternResolutionError, DefaultPatternV1,
    DefaultPatternViewV1, DefaultPlaceIndexError, DefaultPlaceResolutionError, DefaultPlaceV1,
    DefaultPrimitiveBinaryKindV1, DefaultPrimitiveUnaryKindV1, DefaultStatementBuildError,
    DefaultStatementIndexError, DefaultStatementKindV1, DefaultStatementReferenceResolver,
    DefaultStatementResolutionError, DefaultStatementV1, DefaultStringOwnerResolutionError,
    DefaultStringOwnerV1, DefaultTemplateOriginSemanticAuthority,
    DefaultTemplateProviderShapeBuildError, DefaultTemplateProviderShapeV1,
    DefaultTemplateRootSemanticAuthority, DefaultTemplateRootSemanticValidationError,
    DefaultTemplateTypeSubstitutionError, DefaultTryV1, DefaultUnaryOperatorV1, DefaultWhenArmV1,
    DefaultWhenFallbackV1, DefaultWhenFallbackViewV1, DefaultWhenGuardV1, DefaultWhenV1,
    ExportDefaultBodyBuildError, ExportDefaultBodyIndexError, ExportDefaultBodyResolutionError,
    ExportDefaultBodyV1, ExportDefaultTemplateBuildError,
    ExportDefaultTemplateContractSemanticValidationError, ExportDefaultTemplateIndexError,
    ExportDefaultTemplateKeyV1, ExportDefaultTemplateLocalIndexError,
    ExportDefaultTemplateLookupError, ExportDefaultTemplateOriginSemanticValidationError,
    ExportDefaultTemplateResolutionError, ExportDefaultTemplateSetBuildError,
    ExportDefaultTemplateSetEnvelopeSemanticValidationError, ExportDefaultTemplateSetIndexError,
    ExportDefaultTemplateSetValidationError, ExportDefaultTemplateSourceClosureValidationError,
    ExportDefaultTemplateV1, IndexedCanonicalExportDefaultTemplatesV1,
    IndexedCanonicalTemplateValueParametersV1, IndexedDefaultAnonymousFunctionV1,
    IndexedDefaultAppliedOptionV1, IndexedDefaultAssignTargetV1, IndexedDefaultBindingActionV1,
    IndexedDefaultBindingLeafV1, IndexedDefaultBindingPlanV1, IndexedDefaultBindingShapeV1,
    IndexedDefaultBindingTemporaryV1, IndexedDefaultCallableReferenceV1, IndexedDefaultCaptureV1,
    IndexedDefaultCatchV1, IndexedDefaultExpressionV1, IndexedDefaultForIterationPlanV1,
    IndexedDefaultIteratorConformanceV1, IndexedDefaultIteratorNextV1, IndexedDefaultLambdaV1,
    IndexedDefaultLocalFunctionV1, IndexedDefaultPatternV1, IndexedDefaultPlaceV1,
    IndexedDefaultStatementV1, IndexedDefaultTryV1, IndexedDefaultWhenArmV1,
    IndexedDefaultWhenFallbackV1, IndexedDefaultWhenGuardV1, IndexedDefaultWhenV1,
    IndexedExportDefaultBodyV1, IndexedExportDefaultTemplateV1,
    IndexedOptionalDefaultStatementListV1, IndexedOptionalDefaultWhenGuardV1,
    IndexedOptionalTemplateReceiverV1, IndexedTemplateReceiverV1, IndexedTemplateValueParameterV1,
    OptionalDefaultExpressionV1, OptionalDefaultStatementListV1,
    OptionalDefaultStatementListViewV1, OptionalDefaultWhenGuardV1, OptionalTemplateReceiverV1,
    PersistentLexicalRootBuildError, PersistentLexicalRootResolver, PersistentLexicalRootV1,
    TemplateLocalDefinitionV1, TemplateLocalIndexResolver, TemplateLocalLookupError,
    TemplateLocalRecordBuildError, TemplateLocalRecordResolutionError, TemplateLocalRecordV1,
    TemplateLocalReferenceResolver, TemplateLocalScopeValidationError,
    TemplateLocalSelectorResolver, TemplateLocalTableBuildError, TemplateLocalTableValidationError,
    TemplateLocalTypeSemanticValidationError, TemplateReceiverBuildError,
    TemplateReceiverIndexError, TemplateReceiverResolutionError,
    TemplateReceiverSemanticValidationError, TemplateReceiverV1, TemplateValueParameterBuildError,
    TemplateValueParameterIndexError, TemplateValueParameterListBuildError,
    TemplateValueParameterListIndexError, TemplateValueParameterListValidationError,
    TemplateValueParameterResolutionError, TemplateValueParameterSemanticValidationError,
    TemplateValueParameterV1,
};
pub use default_templates::{
    DecodedExportDefaultAccessWitnessV1, DecodedExportDefaultCallableReferenceV1,
    DecodedExportDefaultCallableTargetV1, DecodedExportDefaultConstructorReferenceV1,
    DecodedExportDefaultFieldReferenceV1, DecodedExportDefaultGlobalReferenceV1,
    DecodedExportDefaultReferenceSetV1, DecodedExportDefaultReferenceV1,
    DecodedExportDefaultSingletonReferenceV1, DecodedExportDefaultTypeReferenceV1,
    DefaultReferenceSemanticAuthority, ExportDefaultAccessWitnessV1, ExportDefaultCallDomainV1,
    ExportDefaultCallableReferenceV1, ExportDefaultCallableTargetBuildError,
    ExportDefaultCallableTargetResolutionError, ExportDefaultCallableTargetV1,
    ExportDefaultConstructorReferenceV1, ExportDefaultFieldReferenceV1,
    ExportDefaultGlobalReferenceV1, ExportDefaultReferenceClosureValidationError,
    ExportDefaultReferenceKindV1, ExportDefaultReferenceOccurrenceSiteV1,
    ExportDefaultReferenceResolutionError, ExportDefaultReferenceResolver,
    ExportDefaultReferenceSetBuildError, ExportDefaultReferenceSetSemanticValidationError,
    ExportDefaultReferenceSetV1, ExportDefaultReferenceSetValidationError,
    ExportDefaultReferenceTargetResolutionError, ExportDefaultReferenceTargetTypeSiteV1,
    ExportDefaultReferenceV1, ExportDefaultReferenceValidationError,
    ExportDefaultSingletonReferenceV1, ExportDefaultTargetDomainV1, ExportDefaultTypeReferenceV1,
};
pub use definition_sources::{
    CanonicalExportDefinitionSourcesV1, DecodedCanonicalExportDefinitionSourcesV1,
    DecodedExportDefinitionSourceV1, ExportDefinitionSourceSemanticAuthority,
    ExportDefinitionSourceSemanticValidationError, ExportDefinitionSourceSetBuildError,
    ExportDefinitionSourceSetValidationError, ExportDefinitionSourceV1,
};
pub use nominal_interfaces::{
    CanonicalNominalInterfacesV1, DecodedCanonicalNominalInterfacesV1,
    DecodedNominalInterfaceRecordV1, ExactSupertypeSemanticError, NominalInterfaceRecordBuildError,
    NominalInterfaceRecordResolutionError, NominalInterfaceRecordResolver,
    NominalInterfaceRecordV1, NominalInterfaceSemanticAuthority,
    NominalInterfaceSemanticValidationError, NominalInterfaceSetBuildError,
    NominalInterfaceSetValidationError,
};
pub use nominal_shapes::{
    DecodedEnumSourceFieldV1, DecodedEnumSourceVariantV1, DecodedNominalSourceShapeV1,
    DecodedStructSourceFieldV1, EnumSourceFieldResolutionError, EnumSourceFieldSelectorV1,
    EnumSourceFieldSemanticError, EnumSourceFieldV1, EnumSourceShapeV1,
    EnumSourceVariantBuildError, EnumSourceVariantResolutionError, EnumSourceVariantSemanticError,
    EnumSourceVariantStyleV1, EnumSourceVariantV1, NominalSourceShapeBuildError,
    NominalSourceShapeResolutionError, NominalSourceShapeResolver,
    NominalSourceShapeSemanticAuthority, NominalSourceShapeSemanticError, NominalSourceShapeV1,
    ObjectSourceShapeSemanticError, ObjectSourceShapeV1, StructSourceFieldResolutionError,
    StructSourceFieldSemanticError, StructSourceFieldV1, StructSourceShapeV1,
};
pub use property_interfaces::{
    CanonicalPropertyInterfacesV1, DecodedCanonicalPropertyInterfacesV1,
    DecodedPropertyCapabilityV1, DecodedPropertyInterfaceRecordV1,
    PropertyAccessorClosureValidationError, PropertyCapabilityBuildError,
    PropertyCapabilityResolutionError, PropertyCapabilityV1, PropertyDeclarationIdentityShapeV1,
    PropertyDeclarationSourceShapeV1, PropertyInterfaceRecordBuildError,
    PropertyInterfaceRecordResolutionError, PropertyInterfaceRecordResolver,
    PropertyInterfaceRecordV1, PropertyInterfaceSemanticAuthority,
    PropertyInterfaceSemanticValidationError, PropertyInterfaceSetBuildError,
    PropertyInterfaceSetSemanticValidationError, PropertyInterfaceSetValidationError,
    PropertyPublicAccessV1, PropertyRepresentationV1, PropertySetterPublicAccessV1,
};
pub use public_bindings::{
    CanonicalPublicExportBindingsV1, DecodedCanonicalPublicExportBindingsV1,
    DecodedExportBindingSourceV1, DecodedPublicExportBindingRecordV1, ExportBindingSourceV1,
    PublicExportBindingBuildError, PublicExportBindingRecordV1, PublicExportBindingResolutionError,
    PublicExportBindingResolver, PublicExportBindingSetValidationError,
};
pub use route_closure::{
    PublicExportBindingClosureAuthority, PublicExportBindingClosureValidationError,
};
pub use type_alias_interfaces::{
    CanonicalTypeAliasExpansionsV1, CanonicalTypeAliasInterfacesV1,
    DecodedCanonicalTypeAliasInterfacesV1, DecodedTypeAliasInterfaceRecordV1,
    DecodedTypeAliasTargetV1, TypeAliasClosureAuthority, TypeAliasDeclarationSourceV1,
    TypeAliasExpansionError, TypeAliasExpansionV1, TypeAliasInterfaceRecordBuildError,
    TypeAliasInterfaceRecordResolutionError, TypeAliasInterfaceRecordResolver,
    TypeAliasInterfaceRecordV1, TypeAliasInterfaceSemanticAuthority,
    TypeAliasInterfaceSemanticValidationError, TypeAliasInterfaceSetBuildError,
    TypeAliasInterfaceSetSemanticValidationError, TypeAliasInterfaceSetValidationError,
    TypeAliasTargetResolutionError, TypeAliasTargetV1,
};
