[package]
name = "scoopc"
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "scoopc"
path = "src/main.rs"

[lib]
name = "scoopc"
path = "src/lib.rs"

[dependencies]
cc.workspace = true
clap.workspace = true
scoop-ast.workspace = true
scoop-codegen.workspace = true
scoop-hir-lower.workspace = true
scoop-hir.workspace = true
scoop-lir-lower.workspace = true
scoop-lir.workspace = true
scoop-mir-lower.workspace = true
scoop-mir.workspace = true
scoop-parser.workspace = true
scoop-slib.workspace = true
toml.workspace = true

[dev-dependencies]
insta.workspace = true
