use super::*;

#[derive(Debug, Clone)]
pub struct InterfaceDecl {
    pub name: String,
    pub owner: Option<NominalOwner>,
    pub access: NominalAccess,
    pub self_application: InterfaceApplicationId,
    pub type_params: Vec<TypeParamDecl>,
    pub gc_free_pointee_requirements: Vec<RequiresGcFreePointee>,
    /// Actual local or dependency parent types in declaration order.
    pub parents: Vec<TypeId>,
    /// Methods declared directly by this interface, in itable order after
    /// inherited methods. Inheritance traversal follows `parents` and these
    /// typed ids; consumers never reconstruct ownership from function names.
    pub methods: Vec<InterfaceMethodId>,
    /// Private executable helpers declared directly by this interface. They
    /// have no itable slot and are callable only from the declaring interface.
    pub private_methods: Vec<FunctionId>,
    pub properties: Vec<PropertyId>,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InterfaceApplication {
    pub template: InterfaceId,
    pub arguments: Vec<TypeId>,
    pub canonical_type: TypeId,
}

/// One interface method declaration. Its callable signature and effects live
/// on the directly referenced function; this relation is the authoritative
/// ownership edge and is never recovered by scanning `Module::functions`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InterfaceMethod {
    pub owner: InterfaceId,
    pub function: FunctionId,
    pub role: InterfaceMemberRole,
    pub implementation: InterfaceMemberImplementation,
    /// Interface slots shadowed by this declaration. The relation is typed
    /// and may contain every matching ancestor slot through a diamond.
    pub overrides: Vec<InterfaceMethodReference>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InterfaceMemberRole {
    Function,
    PropertyGetter(PropertyId),
    PropertySetter(PropertyId),
}

/// One interface slot is either executable default code or an abstract
/// obligation. The callable identity remains explicit in both cases.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InterfaceMemberImplementation {
    Body,
    AbstractSlot,
}

/// One complete nominal conformance generated by HIR inheritance checking.
/// `methods` contains an entry for every method in the interface inheritance
/// closure, not only methods declared directly on `interface`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InterfaceImplementation {
    pub interface: TypeId,
    pub methods: Vec<InterfaceMethodImplementation>,
}

/// The declaration of a slot used by one conformance. Dependency slots retain
/// their actual declaring interface and persistent identity.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum InterfaceMethodReference {
    Local(InterfaceMethodId),
    Imported {
        owner: TypeId,
        slot: scoop_identity::PersistentDispatchSlotId,
    },
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InterfaceMethodImplementation {
    pub member: InterfaceMethodReference,
    pub target: InterfaceImplementationTarget,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InterfaceImplementationTarget {
    /// Exact ordinary method application selected by HIR conformance
    /// checking. Generic methods cannot implement interface slots.
    Method(MethodApplicationId),
    Imported(ImportedDependencyCallableUseId),
    ImportedAbstract(ImportedDependencyCallableUseId),
    /// An abstract class may promise an interface while leaving a member for
    /// a concrete subclass. Calls through such a specialization use the
    /// interface application directly instead of guessing a class member.
    Subclass,
}

/// Convenience signature record used by tests and by the fully concrete
/// interface representation. ExportHir interface ownership does not store
/// this record: it stores `InterfaceMethodId -> FunctionId` directly so the
/// declaration identity and callable cannot diverge.
#[derive(Debug, Clone)]
pub struct MethodSig {
    pub name: String,
    pub is_suspend: bool,
    pub attributes: FunctionAttributes,
    pub type_params: Vec<TypeParamDecl>,
    pub params: Vec<Param>,
    pub return_ty: TypeId,
    pub span: Span,
}
