use super::*;

mod queries;

#[derive(Debug, Clone)]
pub struct InterfaceDecl {
    pub name: String,
    pub owner: Option<NominalOwner>,
    pub access: NominalAccess,
    pub definition: InterfaceDefinition,
    pub gc_free_pointee_requirements: Vec<RequiresGcFreePointee>,
    /// Methods declared directly by this interface, in itable order after
    /// inherited methods. Inheritance traversal follows `parents` and these
    /// typed ids; consumers never reconstruct ownership from function names.
    pub methods: Vec<InterfaceMethodId>,
    /// Private executable helpers declared directly by this interface. They
    /// have no itable slot and are callable only from the declaring interface.
    pub private_methods: Vec<FunctionId>,
    pub properties: Vec<PropertyId>,
    pub span: Span,
}

/// Checked parameters and direct parents in the original declaration's scope.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InterfaceDefinition {
    pub self_application: InterfaceApplicationId,
    pub type_params: Vec<TypeParamDecl>,
    pub parents: Vec<TypeId>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LoadedInterfaceDefinition {
    pub declaration: std::sync::Arc<ImportedNominalDeclaration>,
    pub definition: InterfaceDefinition,
    pub methods: Vec<LoadedInterfaceMethod>,
}

impl std::ops::Deref for InterfaceDecl {
    type Target = InterfaceDefinition;

    fn deref(&self) -> &Self::Target {
        &self.definition
    }
}

impl std::ops::DerefMut for InterfaceDecl {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.definition
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LoadedInterfaceMethod {
    pub slot: scoop_identity::CborIdentityRecord<
        scoop_identity::PersistentDispatchSlotId,
        scoop_identity::DispatchSlotKey,
    >,
    pub overrides: Vec<scoop_identity::PersistentDispatchSlotId>,
    pub declaration: CallableDeclarationRecordV1,
    pub name: String,
    pub parameters: Vec<(String, TypeId)>,
    pub return_type: TypeId,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InterfaceApplication {
    pub template: SourceNominalId,
    pub arguments: Vec<TypeId>,
    pub canonical_type: TypeId,
}

/// One interface method declaration. Its callable signature and effects live
/// on the directly referenced function; this relation is the authoritative
/// ownership edge and is never recovered by scanning `Module::functions`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InterfaceMethod {
    pub owner: InterfaceId,
    pub function: FunctionId,
    pub role: InterfaceMemberRole,
    pub implementation: InterfaceMemberImplementation,
    /// Interface slots shadowed by this declaration. The relation is typed
    /// and may contain every matching ancestor slot through a diamond.
    pub overrides: Vec<InterfaceMethodReference>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InterfaceMemberRole {
    Function,
    PropertyGetter(PropertyId),
    PropertySetter(PropertyId),
}

/// One interface slot is either executable default code or an abstract
/// obligation. The callable identity remains explicit in both cases.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InterfaceMemberImplementation {
    Body,
    AbstractSlot,
}

/// One complete nominal conformance generated by HIR inheritance checking.
/// `methods` contains an entry for every method in the interface inheritance
/// closure, not only methods declared directly on `interface`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InterfaceImplementation {
    pub interface: TypeId,
    pub methods: Vec<InterfaceMethodImplementation>,
}

/// The declaration of a slot used by one conformance. Dependency slots retain
/// their actual declaring interface and persistent identity.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum InterfaceMethodReference {
    Local(InterfaceMethodId),
    Imported {
        owner: TypeId,
        slot: scoop_identity::PersistentDispatchSlotId,
    },
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InterfaceMethodImplementation {
    pub member: InterfaceMethodReference,
    pub target: InterfaceImplementationTarget,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InterfaceImplementationTarget {
    /// Exact ordinary method application selected by HIR conformance
    /// checking. Generic methods cannot implement interface slots.
    Method(MethodApplicationId),
    Imported(ImportedDependencyCallableUseId),
    ImportedAbstract(ImportedDependencyCallableUseId),
    ImportedTemplate(ImportedGenericCallableApplicationId),
    ImportedAbstractTemplate(ImportedGenericCallableApplicationId),
    /// The actual abstract declaration retained for a derived implementation.
    Abstract(MethodApplicationId),
}

/// Convenience signature record used by tests and by the fully concrete
/// interface representation. ExportHir interface ownership does not store
/// this record: it stores `InterfaceMethodId -> FunctionId` directly so the
/// declaration identity and callable cannot diverge.
#[derive(Debug, Clone)]
pub struct MethodSig {
    pub name: String,
    pub is_suspend: bool,
    pub attributes: FunctionAttributes,
    pub type_params: Vec<TypeParamDecl>,
    pub params: Vec<Param>,
    pub return_ty: TypeId,
    pub span: Span,
}
