use super::*;

#[derive(Debug, Clone)]
pub struct InterfaceDecl {
    pub name: String,
    pub access: NominalAccess,
    pub self_application: InterfaceApplicationId,
    pub type_params: Vec<TypeParamDecl>,
    /// Exact parent applications in declaration order.
    pub parents: Vec<InterfaceApplicationId>,
    /// Methods declared directly by this interface, in itable order after
    /// inherited methods. Inheritance traversal follows `parents` and these
    /// typed ids; consumers never reconstruct ownership from function names.
    pub methods: Vec<InterfaceMethodId>,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InterfaceApplication {
    pub template: InterfaceId,
    pub arguments: Vec<TypeId>,
    pub canonical_type: TypeId,
}

/// One interface method declaration. Its callable signature and effects live
/// on the directly referenced function; this relation is the authoritative
/// ownership edge and is never recovered by scanning `Module::functions`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct InterfaceMethod {
    pub owner: InterfaceId,
    pub function: FunctionId,
}

/// One complete nominal conformance generated by HIR inheritance checking.
/// `methods` contains an entry for every method in the interface inheritance
/// closure, not only methods declared directly on `interface`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InterfaceImplementation {
    pub interface: InterfaceApplicationId,
    pub methods: Vec<InterfaceMethodImplementation>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InterfaceMethodImplementation {
    pub member: InterfaceMethodId,
    pub target: InterfaceImplementationTarget,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InterfaceImplementationTarget {
    /// Exact ordinary method application selected by HIR conformance
    /// checking. Generic methods cannot implement interface slots.
    Method(MethodApplicationId),
    /// An abstract class may promise an interface while leaving a member for
    /// a concrete subclass. Calls through such a specialization use the
    /// interface application directly instead of guessing a class member.
    Subclass,
}

/// Convenience signature record used by tests and by the fully concrete
/// interface representation. ExportHir interface ownership does not store
/// this record: it stores `InterfaceMethodId -> FunctionId` directly so the
/// declaration identity and callable cannot diverge.
#[derive(Debug, Clone)]
pub struct MethodSig {
    pub name: String,
    pub is_suspend: bool,
    pub attributes: FunctionAttributes,
    pub type_params: Vec<TypeParamDecl>,
    pub params: Vec<Param>,
    pub return_ty: TypeId,
    pub span: Span,
}
