[package]
name = "scoopc_mir"
version.workspace = true
edition.workspace = true

[features]
default = []
llvm = []

[dependencies]
scoopc_ast = { path = "../scoopc_ast" }
scoopc_hir = { path = "../scoopc_hir" }
scoopc_hir_facts = { path = "../scoopc_hir_facts" }
scoopc_ids = { path = "../scoopc_ids" }
scoopc_mir_facts = { path = "../scoopc_mir_facts" }
scoop_project_model = { path = "../scoop_project_model" }
scoopc_source = { path = "../scoopc_source" }
scoopc_span = { path = "../scoopc_span" }
scoopc_types = { path = "../scoopc_types" }
miette = { version = "7.6.0", features = ["fancy"] }
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.12"
tracing = "0.1.40"

[dev-dependencies]
serde_json = "1.0.149"
