[package]
name = "scoop-hir-lower"
edition.workspace = true
rust-version.workspace = true

[dependencies]
la-arena.workspace = true
scoop-ast.workspace = true
scoop-hir.workspace = true
scoop-identity.workspace = true
scoop-wire.workspace = true

[dev-dependencies]
scoop-mir.workspace = true
scoop-mir-lower.workspace = true
