use super::CanonicalHirFoundation;

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct HirFoundationCounts {
    pub sources: usize,
    pub types: usize,
    pub generic_types: usize,
    pub functions: usize,
    pub generic_functions: usize,
    pub constructors: usize,
    pub properties: usize,
    pub extension_properties: usize,
    pub object_values: usize,
    pub type_aliases: usize,
    pub property_accessors: usize,
    pub fields: usize,
    pub enum_variants: usize,
    pub enum_variant_fields: usize,
    pub exact_types: usize,
    pub export_bindings: usize,
    pub callable_applications: usize,
    pub generated_callables: usize,
    pub generated_types: usize,
    pub dispatch_slots: usize,
    pub initialization_units: usize,
    pub source_contexts: usize,
    pub local_bindings: usize,
    pub local_values: usize,
    pub callback_registrations: usize,
    pub source_native_contracts: usize,
    pub odr_groups: usize,
    pub odr_members: usize,
    pub definition_origins: usize,
    pub native_boundary_types: usize,
    pub core_external_source_types: usize,
    pub core_external_generic_types: usize,
}

impl CanonicalHirFoundation {
    pub fn counts(&self) -> HirFoundationCounts {
        HirFoundationCounts {
            sources: self.sources.len(),
            types: self.types.len(),
            generic_types: self.generic_types.len(),
            functions: self.functions.len(),
            generic_functions: self.generic_functions.len(),
            constructors: self.constructors.len(),
            properties: self.properties.len(),
            extension_properties: self.extension_properties.len(),
            object_values: self.object_values.len(),
            type_aliases: self.type_aliases.len(),
            property_accessors: self.property_accessors.len(),
            fields: self.fields.len(),
            enum_variants: self.enum_variants.len(),
            enum_variant_fields: self.enum_variant_fields.len(),
            exact_types: self.exact_types.len(),
            export_bindings: self.export_bindings.len(),
            callable_applications: self.callable_applications.len(),
            generated_callables: self.generated_callables.len(),
            generated_types: self.generated_types.len(),
            dispatch_slots: self.dispatch_slots.len(),
            initialization_units: self.initialization_units.len(),
            source_contexts: self.source_contexts.len(),
            local_bindings: self.local_bindings.len(),
            local_values: self.local_values.len(),
            callback_registrations: self.callback_registrations.len(),
            source_native_contracts: self.source_native_contracts.len(),
            odr_groups: self.odr_groups.len(),
            odr_members: self.odr_members.len(),
            definition_origins: self.definition_origins.len(),
            native_boundary_types: self.native_boundary_types.len(),
            core_external_source_types: self.core_external_source_types.len(),
            core_external_generic_types: self.core_external_generic_types.len(),
        }
    }
}
