[package]
name = "scoopc_hir_facts"
version.workspace = true
edition.workspace = true

[dependencies]
scoopc_ids = { path = "../scoopc_ids" }
scoopc_project_model = { path = "../scoopc_project_model" }
scoopc_source = { path = "../scoopc_source" }
scoopc_span = { path = "../scoopc_span" }
scoopc_types = { path = "../scoopc_types" }
serde = { version = "1.0.228", features = ["derive"] }

[dev-dependencies]
bincode = "1.3.3"
