[package]
name = "scoop-toolchain"
edition.workspace = true
rust-version.workspace = true

[dependencies]
object.workspace = true
scoop-lir.workspace = true
scoop-protocol.workspace = true
scoop-slib.workspace = true
scoop-wire.workspace = true
tempfile.workspace = true
serde.workspace = true
serde_yaml_ng.workspace = true
